configfile: "config.yaml"

from pathlib import Path
import os
import pandas as pd

PROJECT = config["project_root"]
PACKAGE_ROOT = Path(workflow.basedir).resolve().parent
SCRIPTS = PACKAGE_ROOT / "scripts"

SAMPLES_TSV = config["samples_tsv"]
COMPARISON_TSV = config["comparison_tsv"]
DOWNLOAD_JSON = config["download_json"]

REFERENCE_FASTA = config["reference_fasta"]
BOWTIE2_INDEX = config["bowtie2_index"]
HERV_GTF = config["herv_gtf"]
L1_GTF = config["l1_gtf"]

MIN_COUNT = config["min_count"]
ALPHA = config["alpha"]
LOG2FC = config["log2fc_threshold"]

samples_df = pd.read_csv(SAMPLES_TSV, sep="\t")
SAMPLES = samples_df["sample_id"].tolist()


rule all:
    input:
        os.path.join(PROJECT, "results/merged/herv_counts_merged.tsv"),
        os.path.join(PROJECT, "results/merged/l1_counts_merged.tsv"),
        os.path.join(PROJECT, "results/metadata/herv_metadata.tsv"),
        os.path.join(PROJECT, "results/metadata/l1_metadata.tsv"),
        os.path.join(PROJECT, "results/deseq_herv/herv_counts_filtered.tsv"),
        os.path.join(PROJECT, "results/deseq_l1/l1_counts_filtered.tsv"),
        os.path.join(PROJECT, "results/deseq_herv/deseq2_herv.csv"),
        os.path.join(PROJECT, "results/deseq_l1/deseq2_l1.csv"),
        os.path.join(PROJECT, "results/deseq_herv/herv_volcano.png"),
        os.path.join(PROJECT, "results/deseq_l1/l1_volcano.png"),
        os.path.join(PROJECT, "results/deseq_herv/top10_up_herv.csv"),
        os.path.join(PROJECT, "results/deseq_herv/top10_down_herv.csv"),
        os.path.join(PROJECT, "results/deseq_l1/top10_up_l1.csv"),
        os.path.join(PROJECT, "results/deseq_l1/top10_down_l1.csv"),
        os.path.join(PROJECT, "results/deseq_herv/herv_family_enrichment.csv"),
        os.path.join(PROJECT, "results/deseq_l1/l1_family_enrichment.csv"),
        os.path.join(PROJECT, "results/deseq_herv/herv_chromosomal_distribution.csv"),
        os.path.join(PROJECT, "results/deseq_l1/l1_chromosomal_distribution.csv")

rule download_fastq:
    input:
        DOWNLOAD_JSON
    output:
        expand(os.path.join(PROJECT, "results/fastq/{sample}_1.fastq.gz"), sample=SAMPLES),
        expand(os.path.join(PROJECT, "results/fastq/{sample}_2.fastq.gz"), sample=SAMPLES)
    shell:
        f"""
        python {SCRIPTS}/downloader.py \
            -i {input} \
            -d sra \
            -o {PROJECT}/results/fastq
        """
rule download_reference:
    output:
        fasta=os.path.join(PROJECT, REFERENCE_FASTA)
    shell:
        """
        mkdir -p $(dirname {output.fasta})
        wget -O {output.fasta}.gz \
          https://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
        gunzip -f {output.fasta}.gz
        """


rule build_bowtie2_index:
    input:
        fasta=os.path.join(PROJECT, REFERENCE_FASTA)
    output:
        idx1=os.path.join(PROJECT, BOWTIE2_INDEX + ".1.bt2"),
        idx2=os.path.join(PROJECT, BOWTIE2_INDEX + ".2.bt2"),
        idx3=os.path.join(PROJECT, BOWTIE2_INDEX + ".3.bt2"),
        idx4=os.path.join(PROJECT, BOWTIE2_INDEX + ".4.bt2"),
        ridx1=os.path.join(PROJECT, BOWTIE2_INDEX + ".rev.1.bt2"),
        ridx2=os.path.join(PROJECT, BOWTIE2_INDEX + ".rev.2.bt2")
    params:
        prefix=os.path.join(PROJECT, BOWTIE2_INDEX)
    shell:
        """
        mkdir -p $(dirname {params.prefix})
        bowtie2-build {input.fasta} {params.prefix}
        """


rule download_fastq:
    input:
        DOWNLOAD_JSON
    output:
        expand(os.path.join(PROJECT, "results/fastq/{sample}_1.fastq.gz"), sample=SAMPLES),
        expand(os.path.join(PROJECT, "results/fastq/{sample}_2.fastq.gz"), sample=SAMPLES)
    shell:
        """
        python {SCRIPTS}/downloader.py {input}
        """


rule align_and_telescope:
    input:
        fastq1=expand(os.path.join(PROJECT, "results/fastq/{sample}_1.fastq.gz"), sample=SAMPLES),
        fastq2=expand(os.path.join(PROJECT, "results/fastq/{sample}_2.fastq.gz"), sample=SAMPLES),
        samples=SAMPLES_TSV,
        idx1=os.path.join(PROJECT, BOWTIE2_INDEX + ".1.bt2"),
        idx2=os.path.join(PROJECT, BOWTIE2_INDEX + ".2.bt2"),
        idx3=os.path.join(PROJECT, BOWTIE2_INDEX + ".3.bt2"),
        idx4=os.path.join(PROJECT, BOWTIE2_INDEX + ".4.bt2"),
        ridx1=os.path.join(PROJECT, BOWTIE2_INDEX + ".rev.1.bt2"),
        ridx2=os.path.join(PROJECT, BOWTIE2_INDEX + ".rev.2.bt2")
    output:
        expand(os.path.join(PROJECT, "results/bam/{sample}.sorted.bam"), sample=SAMPLES),
        expand(os.path.join(PROJECT, "results/telescope_herv/{sample}/telescope-telescope_report.tsv"), sample=SAMPLES),
        expand(os.path.join(PROJECT, "results/telescope_l1/{sample}/telescope-telescope_report.tsv"), sample=SAMPLES)
    shell:
        """
        python {SCRIPTS}/run_alignment_and_telescope.py {PROJECT}
        """


rule merge_herv:
    input:
        expand(os.path.join(PROJECT, "results/telescope_herv/{sample}/telescope-telescope_report.tsv"), sample=SAMPLES)
    output:
        os.path.join(PROJECT, "results/merged/herv_counts_merged.tsv")
    shell:
        """
        python {SCRIPTS}/merge_telescope_counts.py \
          {PROJECT}/results/telescope_herv \
          {output}
        """


rule merge_l1:
    input:
        expand(os.path.join(PROJECT, "results/telescope_l1/{sample}/telescope-telescope_report.tsv"), sample=SAMPLES)
    output:
        os.path.join(PROJECT, "results/merged/l1_counts_merged.tsv")
    shell:
        """
        python {SCRIPTS}/merge_telescope_counts.py \
          {PROJECT}/results/telescope_l1 \
          {output}
        """


rule build_herv_metadata:
    input:
        HERV_GTF
    output:
        os.path.join(PROJECT, "results/metadata/herv_metadata.tsv")
    shell:
        """
        python {SCRIPTS}/build_locus_metadata.py \
          {input} \
          {output}
        """


rule build_l1_metadata:
    input:
        L1_GTF
    output:
        os.path.join(PROJECT, "results/metadata/l1_metadata.tsv")
    shell:
        """
        python {SCRIPTS}/build_locus_metadata.py \
          {input} \
          {output}
        """


rule filter_herv:
    input:
        counts=os.path.join(PROJECT, "results/merged/herv_counts_merged.tsv"),
        samples=SAMPLES_TSV,
        comparison=COMPARISON_TSV
    output:
        os.path.join(PROJECT, "results/deseq_herv/herv_counts_filtered.tsv")
    shell:
        """
        Rscript {SCRIPTS}/filter_counts.R \
          {input.counts} \
          {input.samples} \
          {input.comparison} \
          {output} \
          {MIN_COUNT}
        """


rule filter_l1:
    input:
        counts=os.path.join(PROJECT, "results/merged/l1_counts_merged.tsv"),
        samples=SAMPLES_TSV,
        comparison=COMPARISON_TSV
    output:
        os.path.join(PROJECT, "results/deseq_l1/l1_counts_filtered.tsv")
    shell:
        """
        Rscript {SCRIPTS}/filter_counts.R \
          {input.counts} \
          {input.samples} \
          {input.comparison} \
          {output} \
          {MIN_COUNT}
        """


rule deseq_herv:
    input:
        counts=os.path.join(PROJECT, "results/deseq_herv/herv_counts_filtered.tsv"),
        samples=SAMPLES_TSV,
        comparison=COMPARISON_TSV
    output:
        csv=os.path.join(PROJECT, "results/deseq_herv/deseq2_herv.csv"),
        png=os.path.join(PROJECT, "results/deseq_herv/herv_volcano.png")
    shell:
        """
        Rscript {SCRIPTS}/run_deseq2_generic.R \
          {input.counts} \
          {input.samples} \
          {input.comparison} \
          {output.csv} \
          {output.png} \
          {ALPHA} \
          {LOG2FC}
        """


rule deseq_l1:
    input:
        counts=os.path.join(PROJECT, "results/deseq_l1/l1_counts_filtered.tsv"),
        samples=SAMPLES_TSV,
        comparison=COMPARISON_TSV
    output:
        csv=os.path.join(PROJECT, "results/deseq_l1/deseq2_l1.csv"),
        png=os.path.join(PROJECT, "results/deseq_l1/l1_volcano.png")
    shell:
        """
        Rscript {SCRIPTS}/run_deseq2_generic.R \
          {input.counts} \
          {input.samples} \
          {input.comparison} \
          {output.csv} \
          {output.png} \
          {ALPHA} \
          {LOG2FC}
        """


rule top_hits_herv:
    input:
        os.path.join(PROJECT, "results/deseq_herv/deseq2_herv.csv")
    output:
        up=os.path.join(PROJECT, "results/deseq_herv/top10_up_herv.csv"),
        down=os.path.join(PROJECT, "results/deseq_herv/top10_down_herv.csv")
    shell:
        """
        Rscript {SCRIPTS}/extract_top_hits.R \
          {input} \
          {ALPHA} \
          {LOG2FC} \
          {output.up} \
          {output.down}
        """


rule top_hits_l1:
    input:
        os.path.join(PROJECT, "results/deseq_l1/deseq2_l1.csv")
    output:
        up=os.path.join(PROJECT, "results/deseq_l1/top10_up_l1.csv"),
        down=os.path.join(PROJECT, "results/deseq_l1/top10_down_l1.csv")
    shell:
        """
        Rscript {SCRIPTS}/extract_top_hits.R \
          {input} \
          {ALPHA} \
          {LOG2FC} \
          {output.up} \
          {output.down}
        """


rule family_enrichment_herv:
    input:
        de=os.path.join(PROJECT, "results/deseq_herv/deseq2_herv.csv"),
        meta=os.path.join(PROJECT, "results/metadata/herv_metadata.tsv")
    output:
        os.path.join(PROJECT, "results/deseq_herv/herv_family_enrichment.csv")
    shell:
        """
        Rscript {SCRIPTS}/family_enrichment.R \
          {input.de} \
          {input.meta} \
          {output} \
          {ALPHA} \
          {LOG2FC}
        """


rule family_enrichment_l1:
    input:
        de=os.path.join(PROJECT, "results/deseq_l1/deseq2_l1.csv"),
        meta=os.path.join(PROJECT, "results/metadata/l1_metadata.tsv")
    output:
        os.path.join(PROJECT, "results/deseq_l1/l1_family_enrichment.csv")
    shell:
        """
        Rscript {SCRIPTS}/family_enrichment.R \
          {input.de} \
          {input.meta} \
          {output} \
          {ALPHA} \
          {LOG2FC}
        """


rule chrom_distribution_herv:
    input:
        de=os.path.join(PROJECT, "results/deseq_herv/deseq2_herv.csv"),
        meta=os.path.join(PROJECT, "results/metadata/herv_metadata.tsv")
    output:
        os.path.join(PROJECT, "results/deseq_herv/herv_chromosomal_distribution.csv")
    shell:
        """
        Rscript {SCRIPTS}/chromosomal_distribution.R \
          {input.de} \
          {input.meta} \
          {output} \
          {ALPHA} \
          {LOG2FC}
        """


rule chrom_distribution_l1:
    input:
        de=os.path.join(PROJECT, "results/deseq_l1/deseq2_l1.csv"),
        meta=os.path.join(PROJECT, "results/metadata/l1_metadata.tsv")
    output:
        os.path.join(PROJECT, "results/deseq_l1/l1_chromosomal_distribution.csv")
    shell:
        """
        Rscript {SCRIPTS}/chromosomal_distribution.R \
          {input.de} \
          {input.meta} \
          {output} \
          {ALPHA} \
          {LOG2FC}
        """
