project_root: /home/a1321/Desktop/lolo/autoretro_ab/my_project

samples_tsv: /home/a1321/Desktop/lolo/autoretro_ab/my_project/config/samples.tsv
comparison_tsv: /home/a1321/Desktop/lolo/autoretro_ab/my_project/config/comparison.tsv
download_json: /home/a1321/Desktop/lolo/autoretro_ab/my_project/config/download.json

reference_fasta: resources/genome/hg38.fa
bowtie2_index: resources/index/hg38

herv_gtf: /home/a1321/Desktop/lolo/autoretro_ab/annotations/HERV_rmsk.hg38.v2.gtf
l1_gtf: /home/a1321/Desktop/lolo/autoretro_ab/annotations/transcripts_with_coords.gtf

threads: 8
min_count: 10
alpha: 0.05
log2fc_threshold: 1

bowtie2_bin: bowtie2
telescope_bin: telescope
